/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_deadmangondk_NativeLib */

#ifndef _Included_com_example_deadmangondk_NativeLib
#define _Included_com_example_deadmangondk_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_deadmangondk_NativeLib
 * Method:    addthem
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_deadmangondk_NativeLib_addthem
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
